### ISSUE TITLE
第8步无法完成

### ISSUE THREAD

**Issue by wangzhenxing4** [sunnyboy-mu/WeChatDiary#1]
在actions中无法运行（原因：没有运行按钮）

**Comment by wangzhenxing4** [comment]
![捕获](https://user-images.githubusercontent.com/79324812/186820712-081023f7-ccd4-4f76-95ba-cffc3b90747b.PNG)

**Comment by wangzhenxing4** [comment]
> 在actions中无法运行（原因：没有运行按钮）

![image](https://user-images.githubusercontent.com/79324812/186820736-830c7f39-ecd7-421d-9477-88a3a3abacaf.png)

**Comment by sunnyboy-mu** [comment]
> 

由于今日测试时，删除了一行代码
请将 `/.github/workflows)/app.yml` 修改为
```
name: WeChatDiary

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js '16.x'
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm ci
      - run: npm run main
```
